version: '3.7'
services:
  mysql:
    image: mysql:8.0.18
    ports:
      - 3306:3306
#    volumes:
#      - ./data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
  postgres:
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
#    volumes:
#      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password